satellites = {
    'AGO' : 10,
    'BEN' : 5,
    'BWA' : 8,
    'BFA' : 5,
    'BDI' : 4,
    'CMR' : 8,
    'CAF' : 6,
    'TCD' : 11,
    'COD' : 30,
    'COG' : 5, 
    'CIV' : 5,
    'DJI' : 2,
    'GNQ' : 2,
    'ERI' : 4,
    'SWZ' : 2,
    'ETH' : 12,
    'GAB' : 5,
    'GMB' : 2,
    'GHA' : 5,
    'GIN' : 5,
    'GNB' : 3,
    'KEN' : 7,
    'LSO' : 2,
    'LBR' : 3,
    'MDG' : 18,
    'MWI' : 5,
    'MLI' : 10,
    'MRT' : 11,
    'MOZ' : 8,
    'NAM' : 10,
    'NER' : 6,
    'NGA' : 10,
    'RWA' : 4,
    'SEN' : 5,
    'SLE' : 4,
    'SOM' : 11,
    'ZAF' : 12,
    'SSD' : 6,
    'SDN' : 18,
    'TZA' : 15,
    'TGO' : 4,
    'UGA' : 7,
    'ZMB' : 9,
    'ZWE' : 5
    
}
 # The number of satellites per decile is obtained by dividing the average area
 # of the decile by 379km^2 corresponding to a hexagon inscribed in a 15-mile 
 # circle that Starlink uses to plan its solid coverage, with an area of 379 
 # square kilometers 
decile_satellites = {
    'Decile 1' : 1,
    'Decile 2' : 2,
    'Decile 3' : 2,
    'Decile 4' : 5,
    'Decile 5' : 7,
    'Decile 6' : 12,
    'Decile 7' : 17,
    'Decile 8' : 8,
    'Decile 9' : 25,
    'Decile 10' : 38   
}